# permissions for end users to edit edgeclustergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ba
    app.kubernetes.io/managed-by: kustomize
  name: edgeclustergroup-editor-role
rules:
- apiGroups:
  - clustergroup.trumpf.com
  resources:
  - edgeclustergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustergroup.trumpf.com
  resources:
  - edgeclustergroups/status
  verbs:
  - get
