# permissions for end users to edit edgeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ba
    app.kubernetes.io/managed-by: kustomize
  name: edgecluster-editor-role
rules:
- apiGroups:
  - clustergroup.trumpf.com
  resources:
  - edgeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustergroup.trumpf.com
  resources:
  - edgeclusters/status
  verbs:
  - get
