---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
<<<<<<< HEAD
  - clusterop.example.com
  resources:
  - clusters
=======
  - clustergroup.trumpf.com
  resources:
  - edgeclusters
>>>>>>> 59ff505 (fix(iter1): added ctrl, crd and sample)
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
<<<<<<< HEAD
  - clusterop.example.com
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - clusterop.example.com
  resources:
  - clusters/status
=======
  - clustergroup.trumpf.com
  resources:
  - edgeclusters/finalizers
  verbs:
  - update
- apiGroups:
  - clustergroup.trumpf.com
  resources:
  - edgeclusters/status
>>>>>>> 59ff505 (fix(iter1): added ctrl, crd and sample)
  verbs:
  - get
  - patch
  - update
